name: Enforce PR Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, edited, synchronize]

jobs:
  require-coupled-label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: minimum
          count: 1
          labels: "0 diff coupled,non 0-diff coupled"
          add_comment: true
          message: "This PR is being prevented from merging because you have not added one of our required labels to say if they are 0-diff or non-0-diff for coupled runs: {{ provided }}. Please add so that the PR can be merged."

  require-dataatm-label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: minimum
          count: 1
          labels: "0 diff dataatm,non 0-diff dataatm"
          add_comment: true
          message: "This PR is being prevented from merging because you have not added one of our required labels to say if they are 0-diff or non-0-diff for dataatm runs: {{ provided }}. Please add so that the PR can be merged."

  require-dataocean-label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: minimum
          count: 1
          labels: "0 diff dataocean,non 0-diff dataocean"
          add_comment: true
          message: "This PR is being prevented from merging because you have not added one of our required labels to say if they are 0-diff or non-0-diff for dataocean runs: {{ provided }}. Please add so that the PR can be merged."

  blocking-label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 0
          labels: "Contingent - DNA,Needs Lead Approval,Contingent -- Do Not Approve"
          add_comment: true
          message: "This PR is being prevented from merging because you have added one of our blocking labels: {{ provided }}. You'll need to remove it before this PR can be merged."
